### ISSUE TITLE
on the About page, the 'statement from the executive producer' and its title are hardcoded

### ISSUE THREAD

**Issue by racepi** [racepi/AboutRace#31]
they should be pulling from the query at the bottom of that file.

**Comment by tam-nguyen** [comment]
@racepi I'd need to confirm. I see the hardcoded content is different with the content query. Are they different ?

**Comment by cf73** [comment]
@tam-nguyen yes that query is showing the updated text, which is what should be displayed.

**Comment by tam-nguyen** [comment]
Thank you!
